# Generated by Django 4.1.4 on 2023-01-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenceStu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_image', models.ImageField(upload_to='', verbose_name='答辩影像')),
                ('self_report', models.CharField(default='', max_length=2000, verbose_name='学生自述内容')),
                ('quiz', models.CharField(default='', max_length=2000, verbose_name='提问与回答')),
            ],
        ),
    ]
