# Generated by Django 4.1.4 on 2023-01-07 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graduate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defencestu',
            name='stu',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defencestu',
            name='quiz',
            field=models.TextField(verbose_name='提问与回答'),
        ),
        migrations.AlterField(
            model_name='defencestu',
            name='self_report',
            field=models.TextField(verbose_name='学生自述内容'),
        ),
    ]
