# Generated by Django 4.1.4 on 2023-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0003_alter_defencestu_def_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defencestu',
            name='def_image',
            field=models.ImageField(upload_to='defence_img/%Y/', verbose_name='答辩影像'),
        ),
    ]
