# Generated by Django 4.1.4 on 2023-01-08 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graduate', '0004_alter_defencestu_def_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=30, verbose_name='职称/选题名称')),
                ('class_name', models.CharField(default='', max_length=30, verbose_name='班级')),
                ('defence_image', models.ImageField(upload_to='defence_img/%Y/', verbose_name='答辩影像')),
                ('self_report', models.TextField(verbose_name='学生自述内容')),
                ('quiz', models.TextField(verbose_name='提问与回答')),
                ('stu', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DefenceStu',
        ),
    ]
