# Generated by Django 4.1.4 on 2023-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sign',
            field=models.ImageField(upload_to='sign_img/', verbose_name='签名/指导教师'),
        ),
    ]
