# Generated by Django 4.1.4 on 2023-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_file', models.FileField(upload_to='file/', verbose_name='教师信息文件')),
            ],
        ),
    ]
