# Generated by Django 4.1.4 on 2023-01-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_instructorbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
